"""Deploy-facing Vietnamese renderer for VLM V2.

The runtime contract stays deliberately simple:
- upstream diagnosis and Recommendation V2 keep authority over item identity/rank;
- Qwen returns only closed-taxonomy visual observations;
- this renderer turns those observations into short, context-aware Vietnamese UI copy.

No free-text explanation is generated by Qwen. Ambiguous or contradictory internal
visual labels are kept for QA only and are not surfaced as user-facing arguments.
"""

from __future__ import annotations

from typing import Mapping

from .pipeline import CATEGORY_LABELS_VI
from .pipeline_v2 import validate_visual_analysis_v2
from .schema_v2 import validate_vlm_evidence_v2


USER_FACING_SCHEMA_VERSION_V2 = "vlm-user-facing-v2"

_CURRENT_ITEM_LABEL_VI = {
    "TOP": "chiếc áo hiện tại",
    "BOTTOM": "món quần/váy hiện tại",
    "DRESS": "chiếc váy liền hiện tại",
    "OUTERWEAR": "chiếc áo khoác hiện tại",
    "SHOES": "đôi giày hiện tại",
    "BAG": "chiếc túi hiện tại",
    "HAT": "chiếc mũ hiện tại",
}

_RECOMMENDATION_NOUN_VI = {
    "TOP": "mẫu áo",
    "BOTTOM": "mẫu quần/váy",
    "DRESS": "mẫu váy liền",
    "OUTERWEAR": "mẫu áo khoác",
    "SHOES": "mẫu giày",
    "BAG": "mẫu túi",
    "HAT": "mẫu mũ",
}

_CONTEXT_NOUN_VI = {
    "TOP": "áo",
    "BOTTOM": "quần/váy",
    "DRESS": "váy liền",
    "OUTERWEAR": "áo khoác",
    "SHOES": "giày",
    "BAG": "túi",
    "HAT": "mũ",
}

_DIAGNOSIS_SUPPORT_PHRASES = {
    "color_harmony": "Màu sắc của món này chưa ăn nhập với {context}.",
    "pattern_coherence": "Họa tiết của món này chưa ăn nhập với {context}.",
    "silhouette_balance": "Phom dáng của món này chưa cân bằng với {context}.",
    "formality_alignment": "Mức độ trang trọng của món này chưa đồng điệu với {context}.",
    "style_coherence": "Phong cách của món này chưa đồng nhất với {context}.",
}

_RECOMMENDATION_SUPPORT_PHRASES = {
    "color_harmony": "Màu sắc phối hợp tốt với {context}.",
    "pattern_coherence": "Họa tiết phối hợp tốt với {context}.",
    "silhouette_balance": "Phom dáng tạo cảm giác cân bằng với {context}.",
    "formality_alignment": "Mức độ trang trọng phù hợp với {context}.",
    "style_coherence": "Phong cách đồng điệu với {context}.",
}


def _join_vi(values: list[str]) -> str:
    unique: list[str] = []
    for value in values:
        if value not in unique:
            unique.append(value)
    if not unique:
        return "các món còn lại"
    if len(unique) == 1:
        return unique[0]
    if len(unique) == 2:
        return f"{unique[0]} và {unique[1]}"
    return ", ".join(unique[:-1]) + f" và {unique[-1]}"


def _context_label(
    indices: list[int],
    problem_index: int,
    category_by_index: Mapping[int, str],
) -> str:
    labels = [
        _CONTEXT_NOUN_VI[category_by_index[index]]
        for index in indices
        if index != problem_index and index in category_by_index
    ]
    return _join_vi(labels)


def _diagnosis_support_reason(
    analysis: Mapping[str, object],
    *,
    problem_index: int,
    category_by_index: Mapping[int, str],
) -> str | None:
    """Return one concise grounded reason only when Qwen supports the diagnosis."""

    if str(analysis["overall_visual_support"]) != "supports_loo":
        return None

    for row in analysis["visual_observations"]:
        if row["effect"] != "supports_loo":
            continue
        context = _context_label(
            list(row["item_indices"]),
            problem_index,
            category_by_index,
        )
        return _DIAGNOSIS_SUPPORT_PHRASES[str(row["dimension"])].format(
            context=context
        )
    return None


def _recommendation_support_reason(
    visual: Mapping[str, object],
    *,
    problem_index: int,
    category_by_index: Mapping[int, str],
) -> str | None:
    """Return one concise relation to the exact context items Qwen referenced."""

    if str(visual["overall_visual_support"]) != "supports_recommendation":
        return None

    for row in visual["visual_observations"]:
        if row["effect"] != "supports_recommendation":
            continue
        context = _context_label(
            list(row["context_item_indices"]),
            problem_index,
            category_by_index,
        )
        return _RECOMMENDATION_SUPPORT_PHRASES[str(row["dimension"])].format(
            context=context
        )
    return None


def render_user_facing_vi_v2(
    analysis: Mapping[str, object],
    evidence: Mapping[str, object],
) -> dict:
    """Render concise UI copy without rank boilerplate or invented visual reasons.

    The UI already knows candidate order from the authoritative rank field, so the
    prose does not repeat "best / second / third". If Qwen has no positive visual
    evidence for an item, the corresponding reason is ``None`` instead of a
    generic fallback sentence.
    """

    normalized_evidence = validate_vlm_evidence_v2(evidence)
    normalized_analysis = validate_visual_analysis_v2(analysis, normalized_evidence)

    diagnosis = normalized_evidence["diagnosis"]
    problem_index = int(diagnosis["problematic_item_index"])
    problem_id = str(diagnosis["problematic_item_id"])
    problem_coarse = str(diagnosis["problematic_category"])
    problem_category = CATEGORY_LABELS_VI[problem_coarse]
    current_item_inline = _CURRENT_ITEM_LABEL_VI[problem_coarse]

    category_by_index = {
        int(row["item_index"]): str(row["coarse_category"])
        for row in normalized_evidence["items"]
    }

    problematic_headline = (
        f"Trong outfit này, {current_item_inline} là món được ưu tiên thay."
    )
    problematic_reason = _diagnosis_support_reason(
        normalized_analysis["diagnosis"],
        problem_index=problem_index,
        category_by_index=category_by_index,
    )

    authoritative_candidates = normalized_evidence["recommendation"]["items"]
    replacement_noun = _RECOMMENDATION_NOUN_VI[problem_coarse]
    all_improve = all(
        float(row["improvement_logit"]) > 0 for row in authoritative_candidates
    )
    if all_improve:
        summary = (
            f"Ba {replacement_noun} bên dưới đều được đánh giá phù hợp hơn khi thay cho "
            f"{current_item_inline}."
        )
    else:
        summary = f"Ba {replacement_noun} bên dưới là các phương án thay thế được ưu tiên."

    analysis_by_id = {
        str(row["item_id"]): row for row in normalized_analysis["recommendations"]
    }

    recommendations: list[dict[str, object]] = []
    reason_sentences: list[str] = []

    for candidate in authoritative_candidates:
        rank = int(candidate["rank"])
        item_id = str(candidate["item_id"])
        coarse_category = str(candidate["coarse_category"])
        display_name = f"{_RECOMMENDATION_NOUN_VI[coarse_category].capitalize()} {rank}"
        reason = _recommendation_support_reason(
            analysis_by_id[item_id],
            problem_index=problem_index,
            category_by_index=category_by_index,
        )

        if reason:
            reason_sentences.append(f"{display_name}: {reason}")

        recommendations.append(
            {
                "rank": rank,
                "item_id": item_id,
                "master_category": str(candidate["master_category"]),
                "coarse_category": coarse_category,
                "display_name": display_name,
                "headline": display_name,
                "reason": reason,
            }
        )

    final_parts = [problematic_headline]
    if problematic_reason:
        final_parts.append(problematic_reason)
    final_parts.append(summary)
    final_parts.extend(reason_sentences)

    closing = "Bạn có thể xem các mẫu bên dưới và chọn phương án phù hợp với sở thích của mình."
    final_text = " ".join(final_parts)

    return {
        "schema_version": USER_FACING_SCHEMA_VERSION_V2,
        "text": final_text,
        "problematic_item": {
            "item_index": problem_index,
            "item_id": problem_id,
            "category": problem_category,
            "headline": problematic_headline,
            "reason": problematic_reason,
        },
        "summary": summary,
        "recommendations": recommendations,
        "caution": closing,
    }
